name: Playwright Tests (Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    # Use Playwright Docker image with Node, browsers, and dependencies
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.1-focal

    defaults:
      run:
        working-directory: 12-Playwright-Introduction-Lab-Resources  # your subfolder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node dependencies
        run: npm ci || npm install

      - name: Start local HTTP server
        run: npm start &
        env:
          PORT: 8080

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:8080

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: 12-Playwright-Introduction-Lab-Resources/playwright-report/

